"""Initial migration

Revision ID: 08fc05376e47
Revises: 
Create Date: 2026-01-05 19:51:16.369621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08fc05376e47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snp_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rs_id', sa.String(length=20), nullable=False),
    sa.Column('chromosome', sa.String(length=5), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('gene_name', sa.String(length=50), nullable=True),
    sa.Column('gene_symbol', sa.String(length=20), nullable=True),
    sa.Column('ref_allele', sa.String(length=10), nullable=True),
    sa.Column('alt_allele', sa.String(length=10), nullable=True),
    sa.Column('minor_allele', sa.String(length=10), nullable=True),
    sa.Column('maf', sa.Float(), nullable=True),
    sa.Column('function_class', sa.String(length=50), nullable=True),
    sa.Column('clinical_significance', sa.String(length=100), nullable=True),
    sa.Column('associated_traits', sa.Text(), nullable=True),
    sa.Column('disease_associations', sa.Text(), nullable=True),
    sa.Column('risk_allele', sa.String(length=10), nullable=True),
    sa.Column('odds_ratio', sa.Float(), nullable=True),
    sa.Column('population_specific', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pubmed_ids', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snp_info_chromosome'), 'snp_info', ['chromosome'], unique=False)
    op.create_index(op.f('ix_snp_info_gene_name'), 'snp_info', ['gene_name'], unique=False)
    op.create_index(op.f('ix_snp_info_rs_id'), 'snp_info', ['rs_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('analysis_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.String(length=100), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('gender_prediction', sa.String(length=20), nullable=True),
    sa.Column('gender_confidence', sa.Float(), nullable=True),
    sa.Column('gender_correct', sa.Boolean(), nullable=True),
    sa.Column('ancestry_prediction', sa.String(length=100), nullable=True),
    sa.Column('ancestry_code', sa.String(length=10), nullable=True),
    sa.Column('ancestry_confidence', sa.Float(), nullable=True),
    sa.Column('ancestry_correct', sa.Boolean(), nullable=True),
    sa.Column('full_results', sa.Text(), nullable=True),
    sa.Column('physical_characteristics', sa.Text(), nullable=True),
    sa.Column('disease_risk_report', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('snp_count', sa.Integer(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_starred', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_history_created_at'), 'analysis_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_history_sample_id'), 'analysis_history', ['sample_id'], unique=False)
    op.create_index(op.f('ix_analysis_history_user_id'), 'analysis_history', ['user_id'], unique=False)
    op.create_table('genetic_risk_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.String(length=100), nullable=False),
    sa.Column('overall_risk_score', sa.Float(), nullable=True),
    sa.Column('cardiovascular_risk', sa.Float(), nullable=True),
    sa.Column('diabetes_risk', sa.Float(), nullable=True),
    sa.Column('cancer_risk', sa.Float(), nullable=True),
    sa.Column('alzheimer_risk', sa.Float(), nullable=True),
    sa.Column('detailed_risks', sa.Text(), nullable=True),
    sa.Column('protective_factors', sa.Text(), nullable=True),
    sa.Column('health_recommendations', sa.Text(), nullable=True),
    sa.Column('lifestyle_recommendations', sa.Text(), nullable=True),
    sa.Column('screening_recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genetic_risk_profiles_sample_id'), 'genetic_risk_profiles', ['sample_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_genetic_risk_profiles_sample_id'), table_name='genetic_risk_profiles')
    op.drop_table('genetic_risk_profiles')
    op.drop_index(op.f('ix_analysis_history_user_id'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_sample_id'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_created_at'), table_name='analysis_history')
    op.drop_table('analysis_history')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_snp_info_rs_id'), table_name='snp_info')
    op.drop_index(op.f('ix_snp_info_gene_name'), table_name='snp_info')
    op.drop_index(op.f('ix_snp_info_chromosome'), table_name='snp_info')
    op.drop_table('snp_info')
    # ### end Alembic commands ###
